### ISSUE TITLE
Svg by name not found

### ISSUE THREAD

**Issue by atmonshi** [Eduard9969/blade-polaris-icons#74]
hey, getting the error
`Svg by name "major-blog" from set "polaris-icons" not found`

I cleared the icons cach and everything
using the last version 1.6.1

**Comment by Eduard9969** [comment]
Hi @atmonshi 

The Shopify repository changed icon naming on the release [v8.0](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris-icons%408.0.0) - It was Removed Major and Minor icon sizing. All icons are the same size.

For the repository, the new icon name skeleton `{icon-name}-icon.svg` instead of `[major|minor]-{icon-name}.svg`, and the new name for `blog` icon `blog-icon`

I changed the release version to [v2.0](https://github.com/Eduard9969/blade-polaris-icons/releases/tag/2.0.0) and removed v1.6. It will help to remove confusion.
You can back to version [v1.5.1](https://github.com/Eduard9969/blade-polaris-icons/releases/tag/1.5.1) to use the major \ minor icon or use [v2](https://github.com/Eduard9969/blade-polaris-icons/releases/tag/2.0.0) with the new icon name.

Polaris icons: [https://polaris-icons.shopify.com/](https://polaris-icons.shopify.com/)

Thanks!
